### PR TITLE
Rename view-configuration to view_configuration to make analyzer happy.

### PR DESCRIPTION
**Pull request by eseidelGoogle**
Analyzer was complaining about '-' not being an allowed character
in dart file names.

R=jamesr@chromium.org

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
@jamesr Testing pull requests.  @Hixie

**Comment by eseidelGoogle** [comment]
I don't see the CLA bot saying anything...

**Comment by jamesr** [comment]
Comment to see if the thingy is workingy

**Comment by jamesr** [comment]
Pinging the robot...

**Pull request merged**
