### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by maqnouch**

### CODE REVIEW

**Comment by maqnouch** [comment]
I signed it!

**Comment by eseidelGoogle** [comment]
lgtm.  @jamesr do we need to modify the AUTHORS file as well, or is this CL OK to land as is?

**Comment by eseidelGoogle** [comment]
Hold tight.  This is our first external pull request and we're still working through all the process details.  We'll get back to you shortly! :)

**Comment by jamesr** [comment]
Process issues sorted.  Is the commit message in the commit here the message that'll show up in the commit log?  Can I ask you to make it a bit more descriptive, for instance say which files you're fixing typos in?

**Comment by eseidelGoogle** [comment]
I was able to edit the commit text when merging.

**Pull request merged**
