### PR TITLE
Added missing semicolon to sample code in README.md.

### PR DESCRIPTION
**Pull request by DanTup**

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks!

**Comment by jamesr** [comment]
Hi Dan!  We aren't taking contributions via pull requests, to contribute patches please go through the workflow described here: https://github.com/domokit/mojo/blob/master/README.md#contribute (or someone with a setup can add this for you).

**Comment by eseidelGoogle** [comment]
I'm working on getting our contribution process revised to include pull requests, until that time, yes my understanding is that we follow the Chromium contribution process documented in that README.  Sorry.

**Comment by DanTup** [comment]
Np! I don't mind doing that if you want; though given the scale of the change (a single character!) not sure if you'd rather just make the change yourselves?

**Comment by eseidelGoogle** [comment]
Thanks.  I've made the change:
https://github.com/domokit/mojo/commit/2db7ab1ed8be93702cad74887149cedab2b06daa

We're in the process of enabling non-googler's to make pull requests as we speak!

**Pull request closed without merging**
